name: SimpleSpawn
author: StevenRafferty
description: A simple spawn plugin with basic commands
main: net.stevenrafferty.SimpleSpawn.Main
version: 0.0.1

commands:
  setspawn:
    description: Sets the spawn on the current players location
    usage: /setspawn
    permission: simplespawn.setspawn
  spawn:
    description: Teleports player to the spawn if one has been set
    usage: /spawn
    permission: simplespawn.spawn
